Repository flow-build/workflow-api, pull requests merged in 2022-09, with the labels that each got.

#70 fix: force type toLowerCase
  src/validators/workflow.js
Labels: js

#71 chore(release): 2.4.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#73 chore(release): 2.5.5
  package-lock.json
  package.json
Labels: dependencies, configuration

#74 Feature/node schemas
  .github/workflows/docker-image-cd.yml
  .github/workflows/release-auto-pr.yml
  package-lock.json
  package.json
  src/controllers/cockpit/nodes.js
  src/routers/cockpitRouter.js
Labels: dependencies, configuration, feature, github-actions, js

#75 chore(release): 2.6.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#76 fix: update engine to 2.16.1
  package-lock.json
  package.json
  src/controllers/state.js
Labels: bug, dependencies, configuration, js

#77 chore(release): 2.6.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#79 chore(release): 2.6.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#80 Fix/adjust tests
  .gitignore
  package-lock.json
  package.json
  src/controllers/cockpit/process.js
  src/controllers/workflow.js
  src/tests/activityManager.test.js
  src/tests/activityManagerValidation.test.js
  src/tests/cockpitProcesses.test.js
  src/tests/cockpitWorkflows.test.js
  src/tests/indexer.test.js
  src/tests/package.test.js
  src/tests/process.test.js
  src/tests/utils/world.js
  src/tests/workflow.test.js
Labels: bug, dependencies, configuration, js, test

#82 chore(release): 2.6.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#81 Feature/basic auth node
  package-lock.json
  package.json
  src/nodes/basicAuthNode.js
  src/nodes/index.js
  src/samples/blueprints/basicAuth.js
Labels: dependencies, configuration, feature, js

#86 Fix/list workflows version
  src/controllers/state.js
  src/controllers/workflow.js
Labels: bug, js

#87 chore(release): 2.7.2
  package-lock.json
  package.json
Labels: dependencies, configuration
