Repository flow-build/workflow-api, pull requests merged in 2022-11, with the labels that each got.

#104 fix: updates engine version with fix for node parameters
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#105 chore(release): 2.11.0-rc.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#107 Fix/update events
  Dockerfile
  db/migrations/20221027150416_add_process_id_foreign_relation.js
  db/migrations/20221028195517_add_target_process_id_column_to_trigger.js
  db/migrations/20221028195535_add_process_state_id_column_to_target.js
  docker-compose.yml
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#108 ci: update create pull request version to v4
  .github/workflows/release-auto-pr.yml
Labels: github-actions

#110 Fix/events migrations
  .github/workflows/release-auto-pr.yml
  db/migrations/20221018153215_create_trigger_table.js
  db/migrations/20221025130847_create_trigger_target_table.js
Labels: bug, github-actions

#111 fix: fix typo on finish node process
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#112 Fix/seeds
  db/seeds/seed-test-core-packages.js
  db/seeds/seed-test-workflow.js
Labels: bug

#113 feat: add pool config to prod
  knexfile.js
Labels: configuration, feature

#114 chore(release): 2.11.0-rc.6
  package-lock.json
  package.json
Labels: dependencies, configuration
