Repository flow-build/workflow-api, pull requests merged in 2023-03, with the labels that each got.

#179 chore(release): 2.19.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#180 chore(release): 2.20.0-development.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#181 Feature/add rabbitmq service
  .env.docker
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/app.js
  src/controllers/healthcheck.js
  src/services/broker/index.js
  src/services/broker/mqtt.js
  src/services/broker/rabbitMQ.js
  src/tests/broker.test.js
  src/utils/engineListener.js
  src/utils/engineLogger.js
Labels: dependencies, configuration, feature, js, test, doc

#182 chore(release): 2.20.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#183 Fix/dockerfile
  Dockerfile
  package.json
  src/server.js
Labels: bug, dependencies, configuration, js

#184 chore(release): 2.20.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#185 fix: adjust mqtt topic key
  src/utils/engineListener.js
Labels: bug, js

#186 chore(release): 2.20.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#187 Add timer management routes
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/controllers/cockpit/activityManager.js
  src/controllers/cockpit/process.js
  src/routers/cockpitRouter.js
  src/samples/blueprints/timersConflicting.js
  src/samples/blueprints/timersConflicting2.js
  src/samples/blueprints/timersDueDate.js
  src/samples/blueprints/timersDuration.js
  src/samples/blueprints/timersDurationProcess.js
  src/samples/blueprints/timersTimeout.js
  src/samples/blueprints/timersTimeoutProcess.js
  src/validators/schemas/nodes.js
Labels: dependencies, configuration, feature, js, doc

#189 fix: update engine to allow disabling timer batch
  db/seeds/seed-test-workflow.js
  package-lock.json
  package.json
  src/controllers/healthcheck.js
Labels: bug, dependencies, configuration, js

#190 build: equalize package & lock
  .github/workflows/auto-merge-release-bump.yml
  package-lock.json
Labels: bug, configuration, github-actions

#192 chore(release): 2.21.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#193 fix: add option to choose status to listen on engineListener
  .env.docker
  README.md
  src/utils/engineListener.js
Labels: bug, configuration, js, doc

#194 chore(release): 2.21.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#195 fix: :card_file_box: add ssl property to prod knex config
  knexfile.js
Labels: bug, configuration

#196 chore(release): 2.21.3
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#197 kafka publish node
  .github/workflows/auto-merge-release-bump.yml
  README.md
  package-lock.json
  package.json
  src/nodes/index.js
  src/nodes/kafkaPublishNode.js
  src/samples/blueprints/kafka.js
  src/services/broker/index.js
  src/services/broker/kafka.js
  src/tests/kafkaPublishNode.test.js
Labels: dependencies, configuration, feature, github-actions, js, test, doc

#199 Update PackageLock
  package-lock.json
  package.json
Labels: bug

#200 chore(release): 2.22.0
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#198 Fix/rabbitmq service
  .env.docker
  README.md
  src/utils/engineListener.js
Labels: configuration, js, doc

#201 chore(release): 2.22.1
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#202 Fix/change kafka lib
  Dockerfile
  package-lock.json
  package.json
  src/services/broker/kafka.js
Labels: bug, dependencies, configuration, js

#204 fix: set broker default to MQTT
  src/utils/engineListener.js
  src/utils/engineLogger.js
Labels: bug, js

#205 chore(release): 2.22.3
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#206 fix: update engine to adjust continue process
  package-lock.json
  package.json
Labels: bug, dependencies, configuration
