Repository flow-build/workflow-api, pull requests merged in 2023-06, with the labels that each got.

#236 Add GraphQL Custom Node
  package-lock.json
  package.json
  src/nodes/graphQlNode.js
  src/nodes/index.js
  src/samples/blueprints/graphQL.js
Labels: dependencies, configuration, feature, js

#238 chore(release): 2.31.0
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#239 fix: fix typo on filename casing
  README.md
  src/nodes/graphqlNode.js
Labels: bug, js, doc

#240 chore(release): 2.31.1
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge
