Repository flow-build/workflow-api, pull requests merged in 2023-05, with the labels that each got.

#216 feat: (WIP) adds historyExecution route on cockpit router
  src/controllers/cockpit/process.js
  src/routers/cockpitRouter.js
Labels: feature, js

#217 feat: (WIP) adds new routes to fetch state execution context
  src/controllers/state.js
  src/routers/mainRouter.js
Labels: feature, js

#218 Package/2.25.0
  package-lock.json
  package.json
  src/controllers/cockpit/process.js
  src/controllers/process.js
  src/controllers/state.js
  src/routers/cockpitRouter.js
  src/routers/mainRouter.js
Labels: dependencies, configuration, js

#220 fix: updates '@flowbuild/nodejs-diagram-builder' package version
  package-lock.json
  package.json
Labels: dependencies, configuration

#221 chore(release): 2.25.1
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#223 feat: update engine to abort & expire process keep bag on state
  package-lock.json
  package.json
Labels: dependencies, configuration, feature

#224 chore(release): 2.26.0
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#222 Feature/flow 98
  .env.docker
  src/controllers/connection.js
  src/routers/cockpitRouter.js
  src/routers/mainRouter.js
Labels: configuration, feature, js

#225 feature: adds extra data on state message to brokers
  src/utils/engineListener.js
Labels: feature, js

#227 chore(release): 2.27.0
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge

#232 feat: changes topic used to publish KAFKA beacon message
  src/controllers/connection.js
Labels: feature, js

#226 feat: add /cockpit/envs routes
  db/migrations/20230516151924_create_environment_variable_table.js
  package-lock.json
  package.json
  src/controllers/cockpit/environmentVariable.js
  src/controllers/workflow.js
  src/routers/cockpitRouter.js
  src/tests/cockpitEnvironmentVariable.test.js
  src/tests/utils/auxiliar.js
  src/validators/base.js
  src/validators/cockpit.js
  src/validators/workflow.js
Labels: dependencies, configuration, feature, js, test

#235 chore(release): 2.30.0
  package-lock.json
  package.json
Labels: dependencies, configuration, automerge
