Repository flow-build/workflow-api, pull requests merged in 2023-01, with the labels that each got.

#140 chore: updates engine version to 2.18.0-beta.2
  db/migrations/20221209134026_create_switch_table.js
  package-lock.json
  package.json
Labels: dependencies, configuration, chore

#141 feat: forcing version update
  README.md
Labels: doc, chore

#142 chore(release): 2.13.0-rc.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#143 feat: updates engine version to 2.19.0-beta.2
  package-lock.json
  package.json
Labels: dependencies, configuration, chore

#144 chore(release): 2.13.0-rc.4
  package-lock.json
  package.json
Labels: dependencies, configuration

#134 chore(release): 2.15.0
  package-lock.json
  package.json
Labels: dependencies, configuration

#145 fix: updates engine version to resolve issue
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#146 chore(release): 2.13.0-rc.5
  package-lock.json
  package.json
Labels: dependencies, configuration

#147 fix: updates engine with http node payload fix
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#148 chore(release): 2.13.0-rc.6
  package-lock.json
  package.json
Labels: dependencies, configuration

#150 Fix/updates packages/merge dev
  package-lock.json
  package.json
  src/nodes/filterDataNode.js
  src/nodes/grpcNode.js
  src/nodes/index.js
  src/samples/blueprints/filterData.js
Labels: bug, dependencies, configuration, js

#151 chore(release): 2.17.0-rc.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#149 fix: updates package versions to solve sec issues
  package-lock.json
  package.json
Labels: bug, dependencies, configuration

#155 chore(release): 2.16.1
  package-lock.json
  package.json
Labels: dependencies, configuration

#156 Fix unit tests execution
  .github/workflows/pr-validation.yml
  package.json
  src/tests/activityManager.test.js
  src/tests/activityManagerValidation.test.js
  src/tests/cockpitBlueprintValidation.test.js
  src/tests/cockpitProcesses.test.js
  src/tests/cockpitWorkflows.test.js
  src/tests/grpcNode.test.js
  src/tests/healthCheck.test.js
  src/tests/indexer.test.js
  src/tests/package.test.js
  src/tests/process.test.js
  src/tests/token.test.js
  src/tests/utils/auxiliar.js
  src/tests/utils/fixtures.js
  src/tests/utils/requestConfig.js
  src/tests/workflow.test.js
Labels: bug, dependencies, configuration, github-actions, js, test

#157 chore(release): 2.16.2
  package-lock.json
  package.json
Labels: dependencies, configuration

#159 chore(release): 2.17.0-rc.3
  package-lock.json
  package.json
Labels: dependencies, configuration

#160 fix: add username and password to mqtt broker connection
  README.md
  src/services/mqtt.js
Labels: bug, js, doc

#161 chore(release): 2.16.3
  package-lock.json
  package.json
Labels: dependencies, configuration
